name: maliks_tasks
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^5.1.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
  remove_alpha_ios: true
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/v2.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    image: assets/v2.png
    #black background
    color: "#ffffff"
    android_gravity: center

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/Vector.png
    - assets/v2.png
    - assets/AppIcon.png
    - .env
